# Generated by Django 5.2.13 on 2026-04-10 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PerformanceAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_tests_taken", models.IntegerField(default=0)),
                ("average_score", models.FloatField(default=0.0)),
                ("highest_score", models.FloatField(default=0.0)),
                ("lowest_score", models.FloatField(default=0.0)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"role": "student"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performance_analytics",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Performance Analytics",
            },
        ),
        migrations.CreateModel(
            name="Suggestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("weak", "Weak Topic"),
                            ("improvement", "Improvement Area"),
                            ("strength", "Strength"),
                            ("resource", "Learning Resource"),
                        ],
                        max_length=20,
                    ),
                ),
                ("topic", models.CharField(max_length=100)),
                ("suggestion_text", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("action_taken", models.BooleanField(default=False)),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"role": "student"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suggestions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TopicPerformance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("topic", models.CharField(max_length=100)),
                ("correct_attempts", models.IntegerField(default=0)),
                ("total_attempts", models.IntegerField(default=0)),
                ("percentage_correct", models.FloatField(default=0.0)),
                ("last_attempted", models.DateTimeField(auto_now=True)),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"role": "student"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topic_performance",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["percentage_correct"],
                "unique_together": {("student", "topic")},
            },
        ),
    ]
